package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of pm_sys_area.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Area implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** area_id. */
	private Integer areaId;

	/** area_name. */
	private String areaName;

	/** parent_id. */
	private Integer parentId;

	/** sort. */
	private Integer sort;

	/** area_code. */
	private String areaCode;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** remarks. */
	private String remarks;

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "Area{" +
				"areaId=" + areaId +
				", areaName='" + areaName + '\'' +
				", parentId=" + parentId +
				", sort=" + sort +
				", areaCode='" + areaCode + '\'' +
				", updateBy='" + updateBy + '\'' +
				", updateTime=" + updateTime +
				", remarks='" + remarks + '\'' +
				'}';
	}
}
