package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_dept.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Dept implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** dept_id. */
	private Integer deptId;

	/** dept_name. */
	private String deptName;

	/** parent_id. */
	private Integer parentId;

	/** sort. */
	private Integer sort;

	/** dept_code. */
	private String deptCode;

	/** master. */
	private String master;

	/** phone. */
	private String phone;

	/** address. */
	private String address;

	/** email. */
	private String email;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getMaster() {
		return master;
	}

	public void setMaster(String master) {
		this.master = master;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "Dept{" +
				"deptId=" + deptId +
				", deptName='" + deptName + '\'' +
				", parentId=" + parentId +
				", sort=" + sort +
				", deptCode='" + deptCode + '\'' +
				", master='" + master + '\'' +
				", phone='" + phone + '\'' +
				", address='" + address + '\'' +
				", email='" + email + '\'' +
				", updateBy='" + updateBy + '\'' +
				", updateTime=" + updateTime +
				", delFlag='" + delFlag + '\'' +
				", remarks='" + remarks + '\'' +
				'}';
	}
}
