package com.tz.cms.sysmgr.entity;

import java.io.Serializable;

/**
 * Model class of pm_sys_role_menu.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysRoleMenu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** pm_sys_role. */
	private Role pmSysRole;

	/** pm_sys_menu. */
	private PmSysMenu pmSysMenu;

	/**
	 * Constructor.
	 */
	public PmSysRoleMenu() {
	}

	/**
	 * Set the pm_sys_role.
	 * 
	 * @param pmSysRole
	 *            pm_sys_role
	 */
	public void setPmSysRole(Role pmSysRole) {
		this.pmSysRole = pmSysRole;
	}

	/**
	 * Get the pm_sys_role.
	 * 
	 * @return pm_sys_role
	 */
	public Role getPmSysRole() {
		return this.pmSysRole;
	}

	/**
	 * Set the pm_sys_menu.
	 * 
	 * @param pmSysMenu
	 *            pm_sys_menu
	 */
	public void setPmSysMenu(PmSysMenu pmSysMenu) {
		this.pmSysMenu = pmSysMenu;
	}

	/**
	 * Get the pm_sys_menu.
	 * 
	 * @return pm_sys_menu
	 */
	public PmSysMenu getPmSysMenu() {
		return this.pmSysMenu;
	}


}
