package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_dept.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysDept implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** dept_id. */
	private Integer deptId;

	/** dept_name. */
	private String deptName;

	/** parent_id. */
	private Integer parentId;

	/** sort. */
	private Integer sort;

	/** dept_code. */
	private String deptCode;

	/** master. */
	private String master;

	/** phone. */
	private String phone;

	/** address. */
	private String address;

	/** email. */
	private String email;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	/** The set of pm_sys_user. */
	private Set<PmSysUser> pmSysUserSet;

	/**
	 * Constructor.
	 */
	public PmSysDept() {
		this.pmSysUserSet = new HashSet<PmSysUser>();
	}

	/**
	 * Set the dept_id.
	 * 
	 * @param deptId
	 *            dept_id
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * Get the dept_id.
	 * 
	 * @return dept_id
	 */
	public Integer getDeptId() {
		return this.deptId;
	}

	/**
	 * Set the dept_name.
	 * 
	 * @param deptName
	 *            dept_name
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * Get the dept_name.
	 * 
	 * @return dept_name
	 */
	public String getDeptName() {
		return this.deptName;
	}

	/**
	 * Set the parent_id.
	 * 
	 * @param parentId
	 *            parent_id
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the parent_id.
	 * 
	 * @return parent_id
	 */
	public Integer getParentId() {
		return this.parentId;
	}

	/**
	 * Set the sort.
	 * 
	 * @param sort
	 *            sort
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * Get the sort.
	 * 
	 * @return sort
	 */
	public Integer getSort() {
		return this.sort;
	}

	/**
	 * Set the dept_code.
	 * 
	 * @param deptCode
	 *            dept_code
	 */
	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	/**
	 * Get the dept_code.
	 * 
	 * @return dept_code
	 */
	public String getDeptCode() {
		return this.deptCode;
	}

	/**
	 * Set the master.
	 * 
	 * @param master
	 *            master
	 */
	public void setMaster(String master) {
		this.master = master;
	}

	/**
	 * Get the master.
	 * 
	 * @return master
	 */
	public String getMaster() {
		return this.master;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the address.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Get the address.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the update_by.
	 * 
	 * @param updateBy
	 *            update_by
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the update_by.
	 * 
	 * @return update_by
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the update_time.
	 * 
	 * @param updateTime
	 *            update_time
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the update_time.
	 * 
	 * @return update_time
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the del_flag.
	 * 
	 * @param delFlag
	 *            del_flag
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the del_flag.
	 * 
	 * @return del_flag
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the remarks.
	 * 
	 * @param remarks
	 *            remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the remarks.
	 * 
	 * @return remarks
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the set of the pm_sys_user.
	 * 
	 * @param pmSysUserSet
	 *            The set of pm_sys_user
	 */
	public void setPmSysUserSet(Set<PmSysUser> pmSysUserSet) {
		this.pmSysUserSet = pmSysUserSet;
	}

	/**
	 * Add the pm_sys_user.
	 * 
	 * @param pmSysUser
	 *            pm_sys_user
	 */
	public void addPmSysUser(PmSysUser pmSysUser) {
		this.pmSysUserSet.add(pmSysUser);
	}

	/**
	 * Get the set of the pm_sys_user.
	 * 
	 * @return The set of pm_sys_user
	 */
	public Set<PmSysUser> getPmSysUserSet() {
		return this.pmSysUserSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((deptId == null) ? 0 : deptId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PmSysDept other = (PmSysDept) obj;
		if (deptId == null) {
			if (other.deptId != null) {
				return false;
			}
		} else if (!deptId.equals(other.deptId)) {
			return false;
		}
		return true;
	}

}
