package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of pm_sys_area.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysArea implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** area_id. */
	private Integer areaId;

	/** area_name. */
	private String areaName;

	/** parent_id. */
	private Integer parentId;

	/** sort. */
	private Integer sort;

	/** area_code. */
	private String areaCode;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	/**
	 * Constructor.
	 */
	public PmSysArea() {
	}

	/**
	 * Set the area_id.
	 * 
	 * @param areaId
	 *            area_id
	 */
	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	/**
	 * Get the area_id.
	 * 
	 * @return area_id
	 */
	public Integer getAreaId() {
		return this.areaId;
	}

	/**
	 * Set the area_name.
	 * 
	 * @param areaName
	 *            area_name
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
	 * Get the area_name.
	 * 
	 * @return area_name
	 */
	public String getAreaName() {
		return this.areaName;
	}

	/**
	 * Set the parent_id.
	 * 
	 * @param parentId
	 *            parent_id
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the parent_id.
	 * 
	 * @return parent_id
	 */
	public Integer getParentId() {
		return this.parentId;
	}

	/**
	 * Set the sort.
	 * 
	 * @param sort
	 *            sort
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * Get the sort.
	 * 
	 * @return sort
	 */
	public Integer getSort() {
		return this.sort;
	}

	/**
	 * Set the area_code.
	 * 
	 * @param areaCode
	 *            area_code
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	/**
	 * Get the area_code.
	 * 
	 * @return area_code
	 */
	public String getAreaCode() {
		return this.areaCode;
	}

	/**
	 * Set the update_by.
	 * 
	 * @param updateBy
	 *            update_by
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the update_by.
	 * 
	 * @return update_by
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the update_time.
	 * 
	 * @param updateTime
	 *            update_time
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the update_time.
	 * 
	 * @return update_time
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the del_flag.
	 * 
	 * @param delFlag
	 *            del_flag
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the del_flag.
	 * 
	 * @return del_flag
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the remarks.
	 * 
	 * @param remarks
	 *            remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the remarks.
	 * 
	 * @return remarks
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((areaId == null) ? 0 : areaId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PmSysArea other = (PmSysArea) obj;
		if (areaId == null) {
			if (other.areaId != null) {
				return false;
			}
		} else if (!areaId.equals(other.areaId)) {
			return false;
		}
		return true;
	}

}
