package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_role.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysRole implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** role_id. */
	private Integer roleId;

	/** role_name. */
	private String roleName;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	/** The set of pm_sys_role_menu. */
	private Set<PmSysRoleMenu> pmSysRoleMenuSet;

	/** The set of pm_sys_user_role. */
	private Set<PmSysUserRole> pmSysUserRoleSet;

	/**
	 * Constructor.
	 */
	public PmSysRole() {
		this.pmSysRoleMenuSet = new HashSet<PmSysRoleMenu>();
		this.pmSysUserRoleSet = new HashSet<PmSysUserRole>();
	}

	/**
	 * Set the role_id.
	 * 
	 * @param roleId
	 *            role_id
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * Get the role_id.
	 * 
	 * @return role_id
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * Set the role_name.
	 * 
	 * @param roleName
	 *            role_name
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * Get the role_name.
	 * 
	 * @return role_name
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * Set the update_by.
	 * 
	 * @param updateBy
	 *            update_by
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the update_by.
	 * 
	 * @return update_by
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the update_time.
	 * 
	 * @param updateTime
	 *            update_time
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the update_time.
	 * 
	 * @return update_time
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the del_flag.
	 * 
	 * @param delFlag
	 *            del_flag
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the del_flag.
	 * 
	 * @return del_flag
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the remarks.
	 * 
	 * @param remarks
	 *            remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the remarks.
	 * 
	 * @return remarks
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the set of the pm_sys_role_menu.
	 * 
	 * @param pmSysRoleMenuSet
	 *            The set of pm_sys_role_menu
	 */
	public void setPmSysRoleMenuSet(Set<PmSysRoleMenu> pmSysRoleMenuSet) {
		this.pmSysRoleMenuSet = pmSysRoleMenuSet;
	}

	/**
	 * Add the pm_sys_role_menu.
	 * 
	 * @param pmSysRoleMenu
	 *            pm_sys_role_menu
	 */
	public void addPmSysRoleMenu(PmSysRoleMenu pmSysRoleMenu) {
		this.pmSysRoleMenuSet.add(pmSysRoleMenu);
	}

	/**
	 * Get the set of the pm_sys_role_menu.
	 * 
	 * @return The set of pm_sys_role_menu
	 */
	public Set<PmSysRoleMenu> getPmSysRoleMenuSet() {
		return this.pmSysRoleMenuSet;
	}

	/**
	 * Set the set of the pm_sys_user_role.
	 * 
	 * @param pmSysUserRoleSet
	 *            The set of pm_sys_user_role
	 */
	public void setPmSysUserRoleSet(Set<PmSysUserRole> pmSysUserRoleSet) {
		this.pmSysUserRoleSet = pmSysUserRoleSet;
	}

	/**
	 * Add the pm_sys_user_role.
	 * 
	 * @param pmSysUserRole
	 *            pm_sys_user_role
	 */
	public void addPmSysUserRole(PmSysUserRole pmSysUserRole) {
		this.pmSysUserRoleSet.add(pmSysUserRole);
	}

	/**
	 * Get the set of the pm_sys_user_role.
	 * 
	 * @return The set of pm_sys_user_role
	 */
	public Set<PmSysUserRole> getPmSysUserRoleSet() {
		return this.pmSysUserRoleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PmSysRole other = (PmSysRole) obj;
		if (roleId == null) {
			if (other.roleId != null) {
				return false;
			}
		} else if (!roleId.equals(other.roleId)) {
			return false;
		}
		return true;
	}

}
