package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_id. */
	private Integer userId;

	/** user_name. */
	private String userName;

	/** login_name. */
	private String loginName;

	/** password. */
	private String password;

	/** user_no. */
	private String userNo;

	/** dept_id. */
	private Integer deptId;

	/** email. */
	private String email;

	/** phone. */
	private String phone;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	/** pm_sys_dept. */
	private PmSysDept pmSysDept;

	/** The set of pm_sys_user_role. */
	private Set<PmSysUserRole> pmSysUserRoleSet;

	/**
	 * Constructor.
	 */
	public PmSysUser() {
		this.pmSysUserRoleSet = new HashSet<PmSysUserRole>();
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the user_name.
	 * 
	 * @param userName
	 *            user_name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the user_name.
	 * 
	 * @return user_name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the login_name.
	 * 
	 * @param loginName
	 *            login_name
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * Get the login_name.
	 * 
	 * @return login_name
	 */
	public String getLoginName() {
		return this.loginName;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the user_no.
	 * 
	 * @param userNo
	 *            user_no
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
	 * Get the user_no.
	 * 
	 * @return user_no
	 */
	public String getUserNo() {
		return this.userNo;
	}

	/**
	 * Set the dept_id.
	 * 
	 * @param deptId
	 *            dept_id
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * Get the dept_id.
	 * 
	 * @return dept_id
	 */
	public Integer getDeptId() {
		return this.deptId;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the update_by.
	 * 
	 * @param updateBy
	 *            update_by
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the update_by.
	 * 
	 * @return update_by
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the update_time.
	 * 
	 * @param updateTime
	 *            update_time
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the update_time.
	 * 
	 * @return update_time
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the del_flag.
	 * 
	 * @param delFlag
	 *            del_flag
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the del_flag.
	 * 
	 * @return del_flag
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the remarks.
	 * 
	 * @param remarks
	 *            remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the remarks.
	 * 
	 * @return remarks
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the pm_sys_dept.
	 * 
	 * @param pmSysDept
	 *            pm_sys_dept
	 */
	public void setPmSysDept(PmSysDept pmSysDept) {
		this.pmSysDept = pmSysDept;
	}

	/**
	 * Get the pm_sys_dept.
	 * 
	 * @return pm_sys_dept
	 */
	public PmSysDept getPmSysDept() {
		return this.pmSysDept;
	}

	/**
	 * Set the set of the pm_sys_user_role.
	 * 
	 * @param pmSysUserRoleSet
	 *            The set of pm_sys_user_role
	 */
	public void setPmSysUserRoleSet(Set<PmSysUserRole> pmSysUserRoleSet) {
		this.pmSysUserRoleSet = pmSysUserRoleSet;
	}

	/**
	 * Add the pm_sys_user_role.
	 * 
	 * @param pmSysUserRole
	 *            pm_sys_user_role
	 */
	public void addPmSysUserRole(PmSysUserRole pmSysUserRole) {
		this.pmSysUserRoleSet.add(pmSysUserRole);
	}

	/**
	 * Get the set of the pm_sys_user_role.
	 * 
	 * @return The set of pm_sys_user_role
	 */
	public Set<PmSysUserRole> getPmSysUserRoleSet() {
		return this.pmSysUserRoleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PmSysUser other = (PmSysUser) obj;
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

}
