package com.tz.cms.sysmgr.entity;

import java.io.Serializable;

/**
 * Model class of pm_sys_user_role.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PmSysUserRole implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** pm_sys_user. */
	private PmSysUser pmSysUser;

	/** pm_sys_role. */
	private PmSysRole pmSysRole;

	/**
	 * Constructor.
	 */
	public PmSysUserRole() {
	}

	/**
	 * Set the pm_sys_user.
	 * 
	 * @param pmSysUser
	 *            pm_sys_user
	 */
	public void setPmSysUser(PmSysUser pmSysUser) {
		this.pmSysUser = pmSysUser;
	}

	/**
	 * Get the pm_sys_user.
	 * 
	 * @return pm_sys_user
	 */
	public PmSysUser getPmSysUser() {
		return this.pmSysUser;
	}

	/**
	 * Set the pm_sys_role.
	 * 
	 * @param pmSysRole
	 *            pm_sys_role
	 */
	public void setPmSysRole(PmSysRole pmSysRole) {
		this.pmSysRole = pmSysRole;
	}

	/**
	 * Get the pm_sys_role.
	 * 
	 * @return pm_sys_role
	 */
	public PmSysRole getPmSysRole() {
		return this.pmSysRole;
	}


}
