package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_role.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Role implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** role_id. */
	private Integer roleId;

	/** role_name. */
	private String roleName;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "Role{" +
				"roleId=" + roleId +
				", roleName='" + roleName + '\'' +
				", updateBy='" + updateBy + '\'' +
				", updateTime=" + updateTime +
				", delFlag='" + delFlag + '\'' +
				", remarks='" + remarks + '\'' +
				'}';
	}
}
