package com.tz.cms.sysmgr.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of pm_sys_user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_id. */
	private Integer userId;

	/** user_name. */
	private String userName;

	/** login_name. */
	private String loginName;

	/** password. */
	private String password;

	/** user_no. */
	private String userNo;

	/** dept_id. */
	private Integer deptId;

	/** email. */
	private String email;

	/** phone. */
	private String phone;

	/** update_by. */
	private String updateBy;

	/** update_time. */
	private Date updateTime;

	/** del_flag. */
	private String delFlag;

	/** remarks. */
	private String remarks;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "User{" +
				"userId=" + userId +
				", userName='" + userName + '\'' +
				", loginName='" + loginName + '\'' +
				", password='" + password + '\'' +
				", userNo='" + userNo + '\'' +
				", deptId=" + deptId +
				", email='" + email + '\'' +
				", phone='" + phone + '\'' +
				", updateBy='" + updateBy + '\'' +
				", updateTime=" + updateTime +
				", delFlag='" + delFlag + '\'' +
				", remarks='" + remarks + '\'' +
				'}';
	}
}
