package com.tz.cms.sysmgr.entity;

import java.io.Serializable;

/**
 * Model class of pm_sys_user_role.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserToRole implements Serializable {
	private Integer userId;
	private Integer roleId;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Override
	public String toString() {
		return "UserToRole{" +
				"userId=" + userId +
				", roleId=" + roleId +
				'}';
	}
}
